In [54]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

# question1
data = pd.read_csv('kc_house_data.csv')

data

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [56]:
#question 2

k=2
# 75% des data pour le fichier d'entrainement. data_1: ensemple d'entraienement
size = 16210
for i in range(k):
    df = data[size*i:size*(i+1)]
    df.to_csv(f'data_{i+1}.csv', index=False)
train_data = pd.read_csv("data_1.csv")
 
test_data = pd.read_csv("data_2.csv")

# Test du code avec la fonction Phi polynomiale

In [57]:
# 1) Matrice Phi,

#type polynomial, phi = xj pour j = 1, .... M-1
x_train = train_data.iloc[:,3:].values
x_test = test_data.iloc[:,3:].values
phi = x_train

t = train_data.iloc[:,2].values
phi

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ..., -1.22257e+02,
         1.34000e+03,  5.65000e+03],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ..., -1.22319e+02,
         1.69000e+03,  7.63900e+03],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ..., -1.22233e+02,
         2.72000e+03,  8.06200e+03],
       ...,
       [ 4.00000e+00,  2.00000e+00,  2.75000e+03, ..., -1.22368e+02,
         1.29000e+03,  1.76400e+03],
       [ 4.00000e+00,  2.50000e+00,  2.57000e+03, ..., -1.22372e+02,
         2.12000e+03,  8.57100e+03],
       [ 3.00000e+00,  1.75000e+00,  1.66000e+03, ..., -1.22162e+02,
         1.26000e+03,  9.68100e+03]])

In [58]:
#initialisation des parametres w, ici 19 parametres car on a 19 features
#w = np.random.randn(18,1)
w = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
w.shape
#w.reshape(18,1)

(18,)

In [59]:
# le Modele
def model (w, phi):
    return phi.dot(w)
model(w, phi)

array([0., 0., 0., ..., 0., 0., 0.])

In [60]:
# fonction erreur, correspondant a E(W)
#def cost_function(phi, t, w):
#    A = np.dot(phi.T, phi)
#    b =  - np.dot(phi.T,t)
#    return 1/2 * np.dot(np.dot(w.T, A), w) + np.dot(b.T, w) + 1/2* np.dot(t.T, t)

def cost_function(phi, t, w):
    e = np.sum((t - model(w,phi))**2)
    return np.sqrt(e)

In [61]:
cost_function(phi, t, w)

82364909.86160202

In [63]:

A = np.dot(phi.T, phi)
b =  - np.dot(phi.T,t)
#Solution Optimale
w_opt = - np.dot(b, np.linalg.inv(A))
#print(w_opt)

# Gradient
def gradient(w):
    A = np.dot(phi.T, phi)
    b =  - np.dot(phi.T,t)
    return np.dot(A,w) + b


def stop(eps, grad):
    norm = np.linalg.norm(grad)
    return norm < eps

def gradient_descent_pas_forte_pente(w0, _max):
    k = 0
    w = w0
    while not stop(0.0001,gradient(w)):
        dk = -gradient(w)
        alpha = -(np.dot(np.dot(dk.T , A), w) + np.dot(dk.T , b)) / (np.dot(np.dot(dk.T,A), dk))
        w = w + alpha*dk
        k = k + 1 
        if k > _max:
            break        
    return w
def gradient_descent_pas_fixe(w0, _max):
    k = 0
    w = w0
    alpha = 0.0001
    while not stop(0.0001,gradient(w)):
        dk = -gradient(w)
        w = w + alpha*dk
        k = k + 1 
        if k > _max:
            break 
    return w

In [64]:

w = gradient_descent_pas_forte_pente(w,10000)
print(w)

[-2.55345707e-02  7.89128012e-02  1.52045504e+02  8.02684070e-02
  1.72236188e-02  2.66558832e-02  2.47997233e-01  8.65958826e-02
  3.04801357e-01  8.34354252e+01  6.86100787e+01 -6.79615453e+00
  4.34806509e+01 -1.09567085e+00  4.90301026e-02 -1.71370437e-02
  9.22716983e+01 -9.00229294e-01]


In [65]:
#fonction cout minimisee
cost_function(phi, t, w)

32586231.00983495

In [66]:
#Prediction sur le test Data

x_test = test_data.iloc[:,3:].values
y_test = test_data.iloc[:,2].values

phi = x_test
predict = model(w, phi)
print(predict)
print(y_test)
df = pd.DataFrame({'price': y_test, 'predicted prices': predict})
df

[460722.23321163 411727.76641327 270196.47006291 ... 211429.15347629
 384888.12310469 211999.10511401]
[565000. 260000. 190000. ... 402101. 400000. 325000.]


price  predicted prices
0     565000.0     460722.233212
1     260000.0     411727.766413
2     190000.0     270196.470063
3     399950.0     631916.016852
4     275000.0     472721.044333
...        ...               ...
5398  360000.0     379059.091875
5399  400000.0     585587.191430
5400  402101.0     211429.153476
5401  400000.0     384888.123105
5402  325000.0     211999.105114

[5403 rows x 2 columns]

# Test du code avec la fonction Phi Sigmoidale

In [67]:
m = 0.55
s = x_train.std()
M = 1000

phi = M * 1/(1 + np.exp(-((x_train - x_train.mean()) / x_train.std())))
phi

array([[426.53508138, 426.51582129, 437.90638745, ..., 425.32928302,
        439.45751547, 481.58888083],
       [426.53508138, 426.52785882, 451.41913073, ..., 425.32868639,
        442.85469359, 501.15745673],
       [426.5254513 , 426.51582129, 433.93722798, ..., 425.32951397,
        452.88199654, 505.32067231],
       ...,
       [426.54471151, 426.5254513 , 453.17466821, ..., 425.32821486,
        438.97265944, 443.57365025],
       [426.54471151, 426.53026633, 451.41913073, ..., 425.32817637,
        447.03566707, 510.3292802 ],
       [426.53508138, 426.52304379, 442.5632927 , ..., 425.33019721,
        438.68180168, 521.24322583]])

In [68]:
#cost function
cost_function(phi, t, w)

63755865.36354084

In [69]:
A = np.dot(phi.T, phi)
b =  - np.dot(phi.T,t)
#Solution Optimale
w_opt = - np.dot(b, np.linalg.inv(A))

# Gradient
def gradient(w):
    A = np.dot(phi.T, phi)
    b =  - np.dot(phi.T,t)
    return np.dot(A,w) + b


def stop(eps, grad):
    norm = np.linalg.norm(grad)
    return norm < eps

def gradient_descent_pas_forte_pente(w0, _max):
    k = 0
    w = w0
    while not stop(0.0001,gradient(w)):
        dk = -gradient(w)
        alpha = -(np.dot(np.dot(dk.T , A), w) + np.dot(dk.T , b)) / (np.dot(np.dot(dk.T,A), dk))
        w = w + alpha*dk
        k = k + 1 
        if k > _max:
            break        
    return w
w = gradient_descent_pas_forte_pente(w,10000)
print(w)

[-2761.39943953 -2750.226012   16694.74126637   -86.97743917
 -2758.40274596 -2757.53070793 -2733.25786964 -2751.59287246
 -2725.56348652  8264.23722818  5558.49798464 -3564.65574169
  2884.34875059 -6233.29452703 -2757.85685254 -2755.29774961
  9360.20066237  -232.0285726 ]


In [71]:

cost_function(phi, t, w)
# on constate que avec la fonction sigmoidale, l'erreur est plus minimiée

32517151.113309205

In [72]:

#Prediction sur le test Data
x_test = test_data.iloc[:,3:].values
y_test = test_data.iloc[:,2].values
test_data
x_test.shape
phi = M * 1/(1 + np.exp(-((x_test - x_test.mean()) / x_test.std())))
phi

array([[427.76981851, 427.76243301, 444.55704747, ..., 426.53748827,
        449.33012844, 517.33674687],
       [427.7796659 , 427.76981851, 442.86898522, ..., 426.53791139,
        446.8429276 , 496.87725194],
       [427.76981851, 427.75012391, 440.19067061, ..., 426.53749811,
        438.50609891, 509.0655955 ],
       ...,
       [427.75997118, 427.7476621 , 437.81286125, ..., 426.53640585,
        437.81286125, 447.60870785],
       [427.76981851, 427.76489484, 443.56391215, ..., 426.53866908,
        441.67820352, 440.45834807],
       [427.75997118, 427.7476621 , 437.81286125, ..., 426.53640585,
        437.81286125, 441.15248756]])

In [73]:
predict = model(w, phi)

df = pd.DataFrame({'price': y_test, 'predicted prices': predict})
df

price  predicted prices
0     565000.0     469403.225489
1     260000.0     430652.156885
2     190000.0     283072.818182
3     399950.0     651607.643141
4     275000.0     497897.389129
...        ...               ...
5398  360000.0     411926.664715
5399  400000.0     615660.293087
5400  402101.0     236945.550117
5401  400000.0     418220.266574
5402  325000.0     238715.241700

[5403 rows x 2 columns]

In [10]:
rng = np.random.default_rng(seed=42)
uu = rng.uniform(low=0,high=1,size=1000)
import numpy as np
u = []
for i in range(1,10,1):
    val = np.sum(uu[:i])/i
    print(val)
    u.append(val)
print(np.sum(uu[:3])/3)
print(u)

0.7739560485559633
0.6064172441540079
0.6904774694064661
0.6922001093196906
0.5725955570332824
0.6397666894671946
0.6571056912562172
0.6732255180088094
0.6126575307495579
0.6904774694064661
[0.7739560485559633, 0.6064172441540079, 0.6904774694064661, 0.6922001093196906, 0.5725955570332824, 0.6397666894671946, 0.6571056912562172, 0.6732255180088094, 0.6126575307495579]
